#pragma once
void EHAC2Menu();
void EHACBMenu();
void EHACRMenu();
void EHAC2PlayerInfoWindow();
void HQLODSAC2();
void TimeOfdayAC2();
void ShadowResolutionAC2();
void CameraFOVAC2();
void InventoryAC2();