#pragma once
void EzioHookAC2Menu();
void EzioHookACBMenu();
void EzioHookACRMenu();
void EzioHookAC2PlayerInfoWindow();
void HQLODSAC2();
void TimeOfdayAC2();
void ShadowResolutionAC2();
void CameraFOVAC2();
void InventoryAC2();